inventory_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from inventory_app import settings
from productapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('productapp.urls', namespace='productapp')),
    path('', TemplateView.as_view(template_name='base.html')),
    path('login/', auth_views.LoginView.as_view(template_name='productapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='productapp:product_list'), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#inventory_app is project

productapp/urls.py
from django.urls import path

from productapp import views
app_name = 'productapp'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),  # 127.0.0.1:8000/products
    path(r'<int:pk>/', views.ProductDetail.as_view(), name='product_detail'),  # 127.0.0.1:8000/products/pk
    path(r'<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),  # 127.0.0.1:8000/products/pk/delete
    path(r'new/', views.ProductCreate.as_view(), name='product_new'),  # 127.0.0.1:8000/products/new
    path(r'<int:pk>/edit/', views.ProductEdit.as_view(), name='product_edit'),
]

productapp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    id = models.IntegerField(primary_key=True)


class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    # category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    price = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)

    def __str__(self):
        return self.name

productapp/forms.py
from django import forms

from productapp.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price')

productapp/views.py
from django.contrib import auth
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from productapp.models import Product, Category
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from productapp.forms import ProductForm


# Create your views here.
class CategoryList(ListView):
    model = Category
    pass


class ProductList(ListView):
    # latest_products = Product.objects.all()
    # context = {'latest_products': latest_products}
    # return render(request, 'productapp/index.html', context)
    template_name = 'productapp/product_list.html'
    model = Product
    context_object_name = 'products'


class ProductDetail(DetailView):
    model = Product
    template_name = 'productapp/product_detail.html'
    context_object_name = 'product'


def product_new(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            prod = form.save(commit=False)
            prod.save()
            return HttpResponseRedirect(reverse('productapp:product_detail', args=(prod.pk,)))
    else:
        form = ProductForm()
        return render(request, 'productapp/product_new.html', {'form': form})


class ProductCreate(CreateView):
    model = Product
    fields = ['name', 'category', 'description', 'price', 'image']
    template_name = 'productapp/product_new.html'
    success_url = reverse_lazy('productapp:product_list')


class ProductEdit(UpdateView):
    model = Product
    template_name = 'productapp/product_edit.html'
    fields = ['name', 'description', 'price', 'image']
    success_url = reverse_lazy('productapp:product_list')


class ProductDelete(DeleteView):
    model = Product
    template_name = 'productapp/product_delete.html'
    success_url = reverse_lazy('productapp:product_list')

productapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django{% endblock title %}</title>
</head>
<body>
    <header>
        {% block header %}
            <p>Login</p>
        {% endblock %}
    </header>
    <div>
        <table width="100%">
            <tr>
                <td colspan="75%"><a href="{% url 'productapp:product_list' %}"> HOME </a></td>
            </tr>
        </table>
    </div>
    <div>
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

productapp/templates/productapp/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title >Title</title>
</head>
<body>
    <h1>{{ product.name }}</h1>
<!--    <image src="{% if question.question_image %}-->
<!--                        {{ question.question_image.url }}-->
<!--                 {% endif %}">-->
<!--    </image>-->


        <image src="{% if product.image %}
                        {{ product.image.url }}
                 {% else %}
                     {% static 'product/no_image.png' %}
                 {% endif %}">
    </image><br>

    {{product.description}} <br>
    ${{product.price}} <br>


    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</body>
</html>

productapp/templates/productapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Hello there

    {% if latest_products %}
        <ul>
        {% for product in latest_products %}
            <li><a href="{% url 'productapp:detail' product.id %}">{{ product }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No products are available.</p>
    {% endif %}
</body>
</html>

productapp/templates/productapp/login.html
{% extends "../base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Login</button>
  </form>
{% endblock content %}

productapp/templates/productapp/logout.html
{% extends "../base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Login</button>
  </form>
{% endblock content %}

productapp/templates/productapp/product_delete.html
{% extends '../base.html' %}


{% block title %}Delete Product{% endblock title %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
        <a href="{% url 'productapp:product_list' %}" > Cancel </a>
    </form>
{% endblock content %}

productapp/templates/productapp/product_detail.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Product Detail{% endblock title %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'product/no_image.png'%} {% endif %}" style="height:50%;width:50%"> <br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {{ product.category }} <br>
    {{ product.description }} <br>
    ${{ product.price }} <br>
{% endblock content %}

productapp/templates/productapp/product_edit.html
{% extends '../base.html' %}

{% block title %}Product Edit{% endblock title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'productapp:product_list' %}" > Cancel </a>
    </form>
{% endblock content %}

productapp/templates/productapp/product_list.html
{% extends '../base.html' %}


{% block title %}Product List{% endblock title %}

{% block content %}
    <a href="{% url 'productapp:product_new' %}">Create new product</a>
    {% if products %}
        <table>
        {% for product in products %}
            <tr>
                <td><a href="{% url 'productapp:product_detail' product.id %}">{{ product.name }}</a></td>
                <td><a href="{% url 'productapp:product_edit' product.id %}">Edit</a></td>
                <td><a href="{% url 'productapp:product_delete' product.id %}">Delete</a></td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No products are available.</p>
    {% endif %}
{% endblock content %}

productapp/templates/productapp/product_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="{% url 'productapp:product_new' %}">{% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'productapp:product_list' %}" > Cancel </a>
    </form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django{% endblock title %}</title>
</head>
<body>
    <header>
        {% block header %}
            <p><a href="{% url 'productapp:login' %}">Login</a></p>
        {% endblock %}
    </header>
    <div>
        <table width="100%">
            <tr>
                <td colspan="75%"><a href="{% url 'productapp:product_list' %}"> HOME </a></td>
            </tr>
        </table>
    </div>
    <div>
        {% block content %}
            Welcome to my products site.
        {% endblock content %}
    </div>
</body>
</html>